name: scroll_app_bar_fork_height
description: Hide or show app bar while scrolling. This package works without custom scroll view and slivers.
version: 1.0.4
homepage: https://github.com/HVLoc/scroll_app_bar.git

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scroll_bars_common: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
